name: Multiple Jobs

on: [push]

jobs:
  build::
    runs-on: ubuntu-latest
    steps:
      - name: Build project
        run: echo "we are creating the build project"
  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test project
        run: echo "this is the test project"